rapid: #namespace

    n_actions: 3 # We have 3 actions, Forwards,TurnLeft,TurnRight

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 0.7 # Speed for going fowards / 0.7
    linear_turn_speed: 0.6 # Linear speed when turning / 0.1
    angular_speed: 0.9 # Angular speed when turning Left or Right
    init_linear_forward_speed: 0.3 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.2 # Initial angular speed in shich we start each episode
    
    new_ranges: 5 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.2 # Minimum meters below which we consider we have crashed
    max_laser_value: 6 # Value considered Ok, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed
    max_linear_aceleration: 18.0 # Linear acceleration value in which we consider RAPID has crashed into something

    max_roll: 1.57 # pi/2
    max_pitch: 1.57 # pi/2

    desired_pose_x: -1.23  # Goal point position
    desired_pose_y: 2.13  # Goal point position
    desired_point_epsilon: 0.5  # Accuracy difference between Goal point and current position
    
    # forwards_reward: 10 # Points Given to go forwards
    turn_reward: 5 # Points Given to turn as action
    get_to_goal_point: 1000 # Points given when arrived at goal point
    closer_to_goal_point: 50 # Points given when closer to goal point
    end_episode_points: 300 # Points given when ending an episode
    

